export type FacilityStatus = "active" | "under_construction" | "planned" | "proposed" | "paused" | "cancelled" | "unknown";
export type ConfidenceLevel = "low" | "medium" | "high";
export type ClaimantType = "company" | "politician" | "activist" | "resident" | "media" | "analyst" | "government";
export type ClaimVerdict = "supported" | "mostly_supported" | "partly_supported" | "unsupported" | "contradicted" | "unclear";
export interface Source { id: string; title: string; publisher?: string; url?: string; published_at?: string; source_type: string; confidence: ConfidenceLevel; notes?: string; }
export interface RiskScore { score: number; confidence: ConfidenceLevel; explanation: string; }
export interface AIRelevance { category: "confirmed" | "likely" | "possible" | "weak_or_unknown"; score: 0|1|2|3|4|5; explanation: string; evidence: string; confidence: ConfidenceLevel; }
export interface Claim { id: string; facility_id: string; exact_claim: string; claimant: string; claimant_type: ClaimantType; date: string; source: string; evidence_for: string[]; evidence_against: string[]; unknowns: string[]; verdict: ClaimVerdict; confidence: ConfidenceLevel; explanation: string; demo_data: boolean; }
export interface Facility { identity:{id:string;name:string;aliases:string[];project_name?:string;owner?:string;operator?:string;developer?:string;known_tenants:string[];suspected_tenants:string[];parent_company?:string;}; location:{state:string;county?:string;city?:string;latitude?:number;longitude?:number;address?:string;approximate_location:boolean;}; status:FacilityStatus; ai_relevance:AIRelevance; scale:{acreage?:number;square_feet?:number;estimated_it_load_mw?:number;estimated_total_load_mw?:number;announced_investment?:number;expected_online_date?:string;}; power:{utility_provider?:string;grid_region?:string;substations:string[];interconnection_notes?:string;backup_generation?:string;diesel_generator_count?:number;grid_strain_risk:RiskScore;}; water:{water_source?:string;cooling_type?:string;estimated_water_use?:string;water_stress_score:RiskScore;water_permits:string[];}; air:{air_permits:string[];diesel_emissions_risk:RiskScore;gas_generation_connection?:string;emissions_notes?:string;}; ecology:{previous_land_use?:string;habitat_risk:RiskScore;wetlands_or_sensitive_area?:string;noise_heat_construction_notes?:string;}; economics:{promised_jobs?:number;permanent_jobs?:number;construction_jobs?:number;tax_abatement_value?:number;subsidy_notes?:string;public_cost_per_permanent_job?:number;}; governance:{elected_officials:string[];agencies:string[];zoning_decisions:string[];public_hearings:string[];opposition:string[];support:string[];transparency_score:RiskScore;}; claims:{claim_ids:string[]}; sources:{source_ids:string[]}; metadata:{verification_status:"needs_verification"|"partially_verified";last_updated:string;confidence:ConfidenceLevel;open_questions:string[];}; }
